### ISSUE TITLE
ansible-galaxy and proper versioning

### ISSUE THREAD

**Issue by astik** [elastic/ansible-beats#12]
Hi,

(aesthetic improvment, not a bug)

Any chance to have this project available in ansible-galaxy ? with a proper stable version ?
It is already done on a sister ansible role (https://github.com/elastic/ansible-elasticsearch) so i guess it should be doable on this one as well.
Yeah, i know i can use it in requirement anyway, but i'd like it ot be consistent =) :

```
- src: elastic.elasticsearch
  version: 6.4.0

- src: https://github.com/elastic/ansible-beats
  version: 1abc778
```

(maybe next step would be kibana =P)

**Comment by jmlrt** [comment]
Hi @astik,
ansible-beats should be available in Ansible Galaxy with a 7.x version following this PR: https://github.com/elastic/ansible-beats/pull/24.

**Comment by jmlrt** [comment]
Beats is now available in Galaxy: https://galaxy.ansible.com/elastic/beats
