### ISSUE TITLE
Mismatch between release name v7.10.1 and version 7.10.1

### ISSUE THREAD

**Issue by Gagarmel** [elastic/ansible-beats#121]
**Beats product**: All

**Beats version**: 7.10.1

**Role version**: v7.10.1 (If using master please specify github sha)

**OS version** (`uname -a` if on a Unix-like system): any

**Description of the problem including expected versus actual behaviour**: 
The latest beats role is published as `v7.10.1`. The specified version in the readme usage section states to use `7.10.1`. Every previous version has been released without starting `v` e.g. `7.10.0`.

**Playbook**: 
No playbook. Just run `ansible-galaxy install elastic.beats,7.10.1`

**Provide logs from Ansible**:
$ ansible-galaxy install elastic.beats,7.10.1

Starting galaxy role install process
downloading role 'beats', owned by elastic
[WARNING]: - elastic.beats was NOT installed successfully: - the specified version (7.10.1) of elastic.beats was not found in the list of available versions ([{'id': 135579,
'url': '', 'related': {}, 'summary_fields': {}, 'created': '2020-09-03T15:46:53.277519Z', 'modified': '2020-09-03T15:46:53.277556Z', 'name': '7.9.1', 'version': '7.9.1',
'commit_date': '2020-09-03T11:43:18-04:00', 'commit_sha': '4ea2a005ed8dccac0623e45e586c9802ec84831c', 'download_url': 'https://github.com/elastic/ansible-
beats/archive/7.9.1.tar.gz', 'active': None}, {'id': 120806, 'url': '', 'related': {}, 'summary_fields': {}, 'created': '2020-03-04T18:09:06.421294Z', 'modified':
'2020-03-04T18:09:06.421322Z', 'name': '7.6.1', 'version': '7.6.1', 'commit_date': '2020-03-04T13:00:59-05:00', 'commit_sha': 'fe677ed42c7fb49149d143285ba57ab654006b4f',
'download_url': 'https://github.com/elastic/ansible-beats/archive/7.6.1.tar.gz', 'active': None}, {'id': 136809, 'url': '', 'related': {}, 'summary_fields': {}, 'created':
'2020-09-24T14:54:52.570184Z', 'modified': '2020-09-24T14:54:52.570220Z', 'name': '7.9.2', 'version': '7.9.2', 'commit_date': '2020-09-24T10:45:49-04:00', 'commit_sha':
'8d69347ddf43de2addd873a08d71c1f7db401840', 'download_url': 'https://github.com/elastic/ansible-beats/archive/7.9.2.tar.gz', 'active': None}, {'id': 129697, 'url': '', 'related':
{}, 'summary_fields': {}, 'created': '2020-06-18T15:13:21.707514Z', 'modified': '2020-06-18T15:13:21.707543Z', 'name': '7.8.0', 'version': '7.8.0', 'commit_date':
'2020-06-18T11:06:57-04:00', 'commit_sha': '12ef312357b5881aabba3c453f07a70533169e14', 'download_url': 'https://github.com/elastic/ansible-beats/archive/7.8.0.tar.gz', 'active':
None}, {'id': 126328, 'url': '', 'related': {}, 'summary_fields': {}, 'created': '2020-05-13T18:03:29.687904Z', 'modified': '2020-05-13T18:03:29.687933Z', 'name': '7.7.0',
'version': '7.7.0', 'commit_date': '2020-05-13T14:01:56-04:00', 'commit_sha': '978875bcd7ca5a9a95596f3cb400976134fd0d7e', 'download_url': 'https://github.com/elastic/ansible-
beats/archive/7.7.0.tar.gz', 'active': None}, {'id': 114101, 'url': '', 'related': {}, 'summary_fields': {}, 'created': '2020-01-21T20:05:03.316237Z', 'modified':
'2020-01-21T20:05:03.316264Z', 'name': '7.5.2', 'version': '7.5.2', 'commit_date': '2020-01-21T14:58:14-05:00', 'commit_sha': '6ea4b5780be25a74d0bd20e5cd98fe6cd2c2e75f',
'download_url': 'https://github.com/elastic/ansible-beats/archive/7.5.2.tar.gz', 'active': None}, {'id': 115673, 'url': '', 'related': {}, 'summary_fields': {}, 'created':
'2020-02-11T17:36:44.807545Z', 'modified': '2020-02-11T17:36:44.807575Z', 'name': '7.6.0', 'version': '7.6.0', 'commit_date': '2020-02-11T12:32:05-05:00', 'commit_sha':
'95994cc60a0fc278e7bae025fa0148f3e42be33c', 'download_url': 'https://github.com/elastic/ansible-beats/archive/7.6.0.tar.gz', 'active': None}, {'id': 133807, 'url': '', 'related':
{}, 'summary_fields': {}, 'created': '2020-08-18T15:31:10.811051Z', 'modified': '2020-08-18T15:31:10.811078Z', 'name': '7.9.0', 'version': '7.9.0', 'commit_date':
'2020-08-18T11:26:57-04:00', 'commit_sha': '82827d16a2d23aea46ba3ed5b864a8e4a263825e', 'download_url': 'https://github.com/elastic/ansible-beats/archive/7.9.0.tar.gz', 'active':
None}, {'id': 111698, 'url': '', 'related': {}, 'summary_fields': {}, 'created': '2019-12-18T19:27:03.483395Z', 'modified': '2019-12-18T19:27:03.483427Z', 'name': '7.5.1',
'version': '7.5.1', 'commit_date': '2019-12-18T14:22:24-05:00', 'commit_sha': 'ae3723679dd0f9f99435992d2d819bd30d6934b8', 'download_url': 'https://github.com/elastic/ansible-
beats/archive/7.5.1.tar.gz', 'active': None}, {'id': 110509, 'url': '', 'related': {}, 'summary_fields': {}, 'created': '2019-12-02T17:47:40.442061Z', 'modified':
'2019-12-02T17:47:40.442089Z', 'name': '7.5.0', 'version': '7.5.0', 'commit_date': '2019-12-02T12:43:50-05:00', 'commit_sha': 'e3ccf93598dcb97b16ef22688a4e70a006d470d7',
'download_url': 'https://github.com/elastic/ansible-beats/archive/7.5.0.tar.gz', 'active': None}, {'id': 138867, 'url': '', 'related': {}, 'summary_fields': {}, 'created':
'2020-10-22T15:24:48.972321Z', 'modified': '2020-10-22T15:24:48.972348Z', 'name': '7.9.3', 'version': '7.9.3', 'commit_date': '2020-10-22T10:32:23-04:00', 'commit_sha':
'1de7b6e8c810d51e94636c2fd7359258a5cba4c7', 'download_url': 'https://github.com/elastic/ansible-beats/archive/7.9.3.tar.gz', 'active': None}, {'id': 93439, 'url': '', 'related':
{}, 'summary_fields': {}, 'created': '2019-05-09T15:02:39.525053Z', 'modified': '2019-05-09T15:02:39.525076Z', 'name': '7.0.0', 'version': '7.0.0', 'commit_date':
'2019-05-09T10:57:40-04:00', 'commit_sha': 'd84339f790431414e42813e10413f5c6d6ca47f4', 'download_url': 'https://github.com/elastic/ansible-beats/archive/7.0.0.tar.gz', 'active':
None}, {'id': 128259, 'url': '', 'related': {}, 'summary_fields': {}, 'created': '2020-06-04T19:37:45.230744Z', 'modified': '2020-06-04T19:37:45.230771Z', 'name': '7.7.1',
'version': '7.7.1', 'commit_date': '2020-06-04T15:33:13-04:00', 'commit_sha': 'd4b5f6da58256179e4ad96f42154f9c7592caacf', 'download_url': 'https://github.com/elastic/ansible-
beats/archive/7.7.1.tar.gz', 'active': None}, {'id': 143086, 'url': '', 'related': {}, 'summary_fields': {}, 'created': '2020-12-09T15:33:49.652250Z', 'modified':
'2020-12-09T15:33:49.652276Z', 'name': 'v7.10.1', 'version': '7.10.1', 'commit_date': '2020-12-09T10:20:12-05:00', 'commit_sha': '14bd3c9321e0718deb802c099c06610d61cea888',
'download_url': 'https://github.com/elastic/ansible-beats/archive/v7.10.1.tar.gz', 'active': None}, {'id': 122753, 'url': '', 'related': {}, 'summary_fields': {}, 'created':
'2020-03-31T17:36:21.632389Z', 'modified': '2020-03-31T17:36:21.632416Z', 'name': '7.6.2', 'version': '7.6.2', 'commit_date': '2020-03-31T13:34:04-04:00', 'commit_sha':
'2a9edd1d680ce6d872d5f3a1df76f4566cd2443d', 'download_url': 'https://github.com/elastic/ansible-beats/archive/7.6.2.tar.gz', 'active': None}, {'id': 132459, 'url': '', 'related':
{}, 'summary_fields': {}, 'created': '2020-07-28T14:39:49.615763Z', 'modified': '2020-07-28T14:39:49.615791Z', 'name': '7.8.1', 'version': '7.8.1', 'commit_date':
'2020-07-28T10:32:03-04:00', 'commit_sha': '0d97824d76eb22eab86c6543ece46e9e5a59cdda', 'download_url': 'https://github.com/elastic/ansible-beats/archive/7.8.1.tar.gz', 'active':
None}, {'id': 140203, 'url': '', 'related': {}, 'summary_fields': {}, 'created': '2020-11-11T15:37:28.802654Z', 'modified': '2020-11-11T15:37:28.802677Z', 'name': '7.10.0',
'version': '7.10.0', 'commit_date': '2020-11-11T10:06:18-05:00', 'commit_sha': 'd792f2a0d2a32ccce8f9c33e6c75ac7605aa1359', 'download_url': 'https://github.com/elastic/ansible-
beats/archive/7.10.0.tar.gz', 'active': None}, {'id': 104836, 'url': '', 'related': {}, 'summary_fields': {}, 'created': '2019-10-01T16:01:47.344857Z', 'modified':
'2019-10-01T16:01:47.344885Z', 'name': '7.4.0', 'version': '7.4.0', 'commit_date': '2019-10-01T11:54:51-04:00', 'commit_sha': '092efb0dcd5358d0582c3a6c2947e8c8f41154dd',
'download_url': 'https://github.com/elastic/ansible-beats/archive/7.4.0.tar.gz', 'active': None}, {'id': 106933, 'url': '', 'related': {}, 'summary_fields': {}, 'created':
'2019-10-23T15:16:07.513213Z', 'modified': '2019-10-23T15:16:07.513238Z', 'name': '7.4.1', 'version': '7.4.1', 'commit_date': '2019-10-23T11:13:22-04:00', 'commit_sha':
'e50cb7f07b914a1a210037e5c7ab7a53913cf6c3', 'download_url': 'https://github.com/elastic/ansible-beats/archive/7.4.1.tar.gz', 'active': None}]).
ERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.

**Beats logs if relevant**:

**Comment by jmlrt** [comment]
Hi @Gagarmel, thanks for reporting this issue.

Indeed, we changed our release process and this involved having the `v` prefix in the ansible-beats Git tags. Unfortunately we missed that this would involve a change in the Ansible Galaxy install command.

The new command is now `ansible-galaxy install elastic.beats,v7.10.1`.

I'll update it in the repo README.

Does that look fine with you?

Sorry for the trouble.

**Comment by Gagarmel** [comment]
Hi @jmlrt,

thank you for your fast reply. I'm totally fine with the new naming.
I've already changed it in our CI scripts.

I just wasn't sure if it was changed on purpose or by mistake. :)
