### ISSUE TITLE
elastic.beats was NOT installed successfully: Unable to compare role versions

### ISSUE THREAD

**Issue by euskadi31** [elastic/ansible-beats#141]
```bash
ansible-galaxy install elastic.beats --force                
- changing role elastic.beats from 7.9.2 to unspecified
- downloading role 'beats', owned by elastic
[WARNING]: - elastic.beats was NOT installed successfully: Unable to compare role versions (7.0.0, 7.4.0, 7.4.1, 7.5.0, 7.5.1, 7.5.2, 7.6.0, 7.6.1, 7.6.2, 7.7.0, 7.7.1, 7.8.0, 7.8.1, 7.9.0, 7.9.1,
7.9.2, 7.9.3, 7.10.0, v7.10.1, v7.10.2, v7.11.1, v7.11.2, v7.12.0) to determine the most recent version due to incompatible version formats. Please contact the role author to resolve versioning
conflicts, or specify an explicit role version to install.
```

**Comment by kd8drx** [comment]
Heya @euskadi31! https://github.com/elastic/ansible-beats/issues/121#issuecomment-742537672 has more details on what's happening here, but in short it's expected. 

To address, manually specify the version you want to install, e.g. `ansible-galaxy install elastic.beats,v7.12.0`. If you don't specify what version to install, this error will occur as more recent build strings are prefixed with `v`, which `ansible-galaxy` has a hard time with.
