### ISSUE TITLE
Avoid locking beats_version and provide documentation.

### ISSUE THREAD

**Issue by clin88** [elastic/ansible-beats#15]
The role defaults to beats_version 6.2.1. This was rather surprising and undocumented behavior, and would likely be confusing for others. For example, docs for the latest version of filebeat references "filebeat.inputs", which didn't exist in 6.2.1. Filebeat fails quietly when a key is present in config it doesn't expect, causing me to spend a few hours to find the root cause.

Instead, the version should probably be a required variable, just like beats_conf. Users can then choose which version to pin.

**Comment by jmlrt** [comment]
Hi @clin88,

Sorry for the delay to answer.

Actually the `beats_version` is a variable defined here: https://github.com/elastic/ansible-beats/blob/master/defaults/main.yml#L13
It is set by default to `6.2.4` and you can override when calling ansible-beats role to the version you want (7.x is not supported yet by this role).

**Comment by jmlrt** [comment]
FYI I created https://github.com/elastic/ansible-beats/pull/21 to update doc and improve variables descriptions.

**Comment by clin88** [comment]
Ya, I think the main ask was to be clearer in the docs. It may be preferable to avoid having a default and require users specify a version. My expectation was that this would pull in the latest version by default.

That said get this would be a breaking change so probably not feasible :P.

**Comment by jmlrt** [comment]
Yeah, role update to support beats 7.x is in progress (cf. https://github.com/elastic/ansible-beats/tree/beats-7.x). When it will be ready, beats 7.0.0 (or the latest version) will be the default version.

**Comment by jmlrt** [comment]
I'm closing the issue, don't hesitate to reopen it if you have any question.
