### ISSUE TITLE
Pin repository OpenPGP fingerprint 

### ISSUE THREAD

**Issue by ypid-geberit** [elastic/ansible-beats#30]
As mentioned in https://github.com/elastic/ansible-beats/issues/2#issuecomment-482006591, additionally to use https to download the key, it should be pinned. The pinning has additional benefits because what should the OpenPGP key actually protect against? -> Compromised webservers in case we already have TLS.

Currently the key comes from: https://packages.elastic.co/GPG-KEY-elasticsearch
And the repo: https://artifacts.elastic.co/packages/

They are both hosted by fastly.net. So currently, adding the OpenPGP key or just accepting not trusted sources does not make much difference from a security point of view.

@jmlrt You just closed https://github.com/elastic/ansible-beats/issues/2 without tracking that the actual issue still persists.

**Comment by jmlrt** [comment]
Hello @ypid-geberit,

Thank you for this new issue.

I closed https://github.com/elastic/ansible-beats/issues/2 which was about using https url for downloading gpg key. That is already done so I consider this issue fixed.

We'll manage this new issue soon.

You can also send us a PR to add this feature using code present in https://github.com/debops/debops/blob/d9713de0f2d9b0be8c0d553bc8ec47f9a1dd6835/ansible/roles/debops.elastic_co/tasks/main.yml#L4-L5.

**Comment by ypid-geberit** [comment]
Still valid in my eyes. If the bot could be so kind an leave the issue open, that would be great :)

**Comment by ypid-geberit** [comment]
Still valid from my point of view. Note that I already gave examples of how to implement this in https://github.com/elastic/ansible-beats/issues/2#issuecomment-482006591

**Comment by ypid-geberit** [comment]
Unless the bot can implement this feature, could it be disabled for this feature somehow?

**Comment by ypid-geberit** [comment]
To restate. This issue is still valid. I simply don’t want to deal with the bot any longer so I give up. I don’t even use this Ansible role. I just wanted to help you out by basically giving you the full solution. Just doing a PR seems like too much to ask for. I have no need for this role. I am happy with the Elastic support we have at DebOps where this issue is properly solved for years already. Ref: https://docs.debops.org/en/master/ansible/roles/elastic_co/index.html

I unsubscribed from this issue. Feel free to ping me with my user handle as needed.
