### ISSUE TITLE
Add support for Auditbeat, Heartbeat and Functionbeat

### ISSUE THREAD

**Issue by jmlrt** [elastic/ansible-beats#42]
This Ansible role currently support [Filebeat](https://www.elastic.co/products/beats/filebeat), [MetricBeat](https://www.elastic.co/products/beats/metricbeat) and [Packetbeat](https://www.elastic.co/products/beats/packetbeat).

We should also support the other official Beats: [Auditbeat](https://www.elastic.co/products/beats/auditbeat), [Heartbeat](https://www.elastic.co/products/beats/heartbeat) and [FunctionBeat](https://www.elastic.co/products/beats/functionbeat).

Note that supporting [Winlogbeat](https://www.elastic.co/products/beats/winlogbeat) would require Windows support which we currently don't have (see #17 and #27).

Related to #36 

**Tasks**

- [ ] Add 3 new [integration tests](https://github.com/elastic/ansible-beats/tree/master/test/integration) which will deploy and validate each of the new Beats to support

**Comment by sachinfrayne** [comment]
Heartbeat workaround:

```
- name: Example playbook for installing heartbeat
  hosts: localhost
  roles:
    - {
        role: elastic.beats,
        beat: "heartbeat-elastic",
        beats_conf_dir: "/etc/heartbeat",
        conf_file: "/etc/heartbeat/heartbeat.yml",
        beat_conf: {
          "heartbeat": {
            "monitors": [
              {
                "type": "http",
                "schedule": "@every 5s",
                "urls": ["http://elastic.co"],
                "check.response.status": 301,
                "name": "elastic.co"
              }
            ]
          }
        },
        output_conf : {
          "elasticsearch": {
            "hosts": ["localhost:9200"]
          }
        }
      }
```

**Comment by jmlrt** [comment]
👍

**Comment by jmlrt** [comment]
still valid

**Comment by accu-joeykarns** [comment]
Still Valid and very helpful since...heartbeat seems to be the one with the extra "-elastic" in the package name

**Comment by Pluggi** [comment]
> Heartbeat workaround:
> 
> ```
> - name: Example playbook for installing heartbeat
>   hosts: localhost
>   roles:
>     - {
>         role: elastic.beats,
>         beat: "heartbeat-elastic",
>         beats_conf_dir: "/etc/heartbeat",
>         conf_file: "/etc/heartbeat/heartbeat.yml",
>         beat_conf: {
>           "heartbeat": {
>             "monitors": [
>               {
>                 "type": "http",
>                 "schedule": "@every 5s",
>                 "urls": ["http://elastic.co"],
>                 "check.response.status": 301,
>                 "name": "elastic.co"
>               }
>             ]
>           }
>         },
>         output_conf : {
>           "elasticsearch": {
>             "hosts": ["localhost:9200"]
>           }
>         }
>       }
> ```

This doesn't seem to work because of this `set_fact`:
https://github.com/elastic/ansible-beats/blob/eb3aad82d1cf36fc1331cecabcd14761de62acf0/tasks/beats-config.yml#L8

which takes precedence over any `conf_file` defined before.

**Comment by Pluggi** [comment]
An other workaround is to use an override file

```
# cat /etc/systemd/system/heartbeat-elastic.service.d/override.conf
[Service]
Environment="BEAT_CONFIG_OPTS=-c /etc/heartbeat/heartbeat-elastic.yml"
```

**Comment by vxavictor513** [comment]
bump!
