### ISSUE TITLE
Add journalbeat tests/support

### ISSUE THREAD

**Issue by houstdav000** [elastic/ansible-beats#80]
Journalbeat is listed as experimental
https://www.elastic.co/guide/en/beats/journalbeat/master/index.html

but has been merged into the main beats repository.

The potential for integration directly into journald (checks may have to be required in order to verify journald is present) is great, since you can then directly log from systemd units.

**Comment by jmlrt** [comment]
Hi @houstdav000,
Thanks for submitting this feature request. I don't think we'll add Journalbeat support while it's experimental. We still have Auditbeat, Heartbeat and Functionbeat support to add before.

**Comment by jmlrt** [comment]
still valid
