### ISSUE TITLE
Error during "unhold filebeat version for install"

### ISSUE THREAD

**Issue by dawi** [elastic/ansible-beats#83]
**Beats product**: Filebeat

**Beats version**: 7.6.1

**OS version** (`uname -a` if on a Unix-like system):

* Ubuntu 18.04.
* Linux xxx 4.15.0-76-generic #86-Ubuntu SMP Fri Jan 17 17:24:28 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behaviour**:

I would like to install filebeat via this role and provide a custom package url.

```
beat: filebeat
use_repository: false
custom_package_url: "https://xxx/filebeat/filebeat-7.6.1-amd64.deb"
beat_conf:
  filebeat:
    xxx
```

But this fails with the following error: 

```
TASK [elastic.beats : Debian - unhold filebeat version for install] **********************************************************************************************************************************************************************************************************
fatal: [xxx]: FAILED! => changed=false 
  cmd:
  - apt-mark
  - unhold
  - filebeat
  delta: '0:00:00.099800'
  end: '2020-04-08 16:10:52.052093'
  msg: non-zero return code
  rc: 100
  start: '2020-04-08 16:10:51.952293'
  stderr: |-
    E: Paket filebeat kann nicht gefunden werden.
    E: Keine Pakete gefunden
  stderr_lines: <omitted>
  stdout: ''
  stdout_lines: <omitted>
```

The issue seems to be that the following task is always executed:

```
- name: Debian - unhold {{ beat }} version for install
  command: apt-mark unhold {{ beat }}
  changed_when: false
```

Without this task, everything runs fine.

**Comment by jmlrt** [comment]
still valid

**Comment by jmlrt** [comment]
👍

**Comment by jonesbusy** [comment]
Same issue here, cannot use the module to download with 'custom_package_url: https://artifacts.elastic.co/downloads/beats/packetbeat/packetbeat-7.12.1-arm64.deb'
